### ISSUE TITLE
Intense peformance loss.

### ISSUE THREAD

**Issue by IMB11** [Raemien/MRCPlus#12]
When MRC is enabled via OBS "Connect to MRC-enabled game...", framerate drops from 90fps to 5-15fps.

Logs attached.

Mod List:

![](https://cal.has-no-bra.in/5k9jS_7vV.png)
![](https://cal.has-no-bra.in/5k9jOsYuB.png)
![](https://cal.has-no-bra.in/5k9jJ8uaw.png)

**Comment by IMB11** [comment]
[BMBFservice.log](https://github.com/Raemien/MRCPlus/files/7801837/BMBFservice.log)
[MRCPlus_1_0_1.log](https://github.com/Raemien/MRCPlus/files/7801847/MRCPlus_1_0_1.log)

**Comment by Raemien** [comment]
Hi there!

Due to how Oculus MRC is implemented in Unity applications, Beat Saber's framerate is strictly tied to the time it takes your PC to receive and decode video data from your Quest. As such, poor network conditions and lack of resources on the client PC can cause major framerate issues. I'd recommend reducing overall network traffic across all devices and moving closer to your wireless router/hotspot to reduce game lag.

Let me know if this helps.
Cheers!

**Comment by IMB11** [comment]
Using an ethernet connection straight to my pc fixed all lag. thanks :)
