### ISSUE TITLE
white bar at the side of the screen with aika tweaks bloom enabled

### ISSUE THREAD

**Issue by imalpha75** [Raemien/MRCPlus#17]
if anyone knows any solutions to this problem please send it here

**Comment by Raemien** [comment]
Hi there! This is a known issue with AnyTweaks - its bloom post-processing effect causes this line to appear during scene transitions. While this visual bug isn't something that can be fixed in MRCPlus, you can temporarily work around this issue through disconnecting for a few seconds to discard the temporary frame buffer.
